[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tui"
version = "0.2.0"
description = "Customisable 4-panel (axial / sagittal / coronal / 3D) medical image viewer with temporal data and markup."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    {name = "Fraser M. Callaghan", email = "callaghan.fm@gmail.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
dependencies = [
    "vtk>=9.3",
    "PyQt5>=5.15.10",
    "numpy>=1.21",
    "scipy>=1.7",
    "ngawari",
]
license = { file = "LICENSE" }

[project.optional-dependencies]
dicom = ["spydcmtk>=1.2.14"]

[project.scripts]
tui = "tui.cli:main"

[tool.setuptools.packages.find]
include = ["tui*"]
exclude = ["tests", "*.tests", "*.tests.*", "tests.*"]

[tool.setuptools]
include-package-data = true

[project.urls]
Homepage = "https://github.com/fraser29/tui"
